language: objective-c
osx_image: xcode7
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S" SCHEME="Signals" SDK=iphonesimulator9.0
    - DESTINATION="OS=8.2,name=iPhone 5" SCHEME="Signals" SDK=iphonesimulator9.0
    - DESTINATION="OS=8.3,name=iPhone 5S" SCHEME="Signals" SDK=iphonesimulator9.0
    - DESTINATION="OS=8.4,name=iPhone 6" SCHEME="Signals" SDK=iphonesimulator9.0
    - DESTINATION="OS=9.0,name=iPhone 6 Plus" SCHEME="Signals" SDK=iphonesimulator9.0
before_install:
  - gem install cocoapods slather -N
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project Signals.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION"
    -configuration Debug ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES test | xcpretty -c
after_success: slather
notifications:
  email: false